sparklines:
  - title: CPU usage
    position: [[0, 9], [20, 5]]
    rate-ms: 200
    scale: 0
    sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
  - title: Free memory pages
    position: [[0, 14], [16, 7]]
    rate-ms: 200
    scale: 0
    sample: memory_pressure | grep 'Pages free' | awk '{print $3}'
textboxes:
  - title: Local weather
    position: [[0, 0], [27, 7]]
    rate-ms: 10000
    color: 178
    sample: curl wttr.in?0ATQF
    border: false
asciiboxes:
  - title: PST time
    position: [[27, 0], [53, 9]]
    rate-ms: 500
    color: 43
    sample: env TZ=US/Pacific date +%r
    border: false
    font: 3d
