# Inserts a blank line between shell prompts
add_newline = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[>](blue)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
