theme = "base16_default_dark"

[editor]
scrolloff = 7
cursorline = true
bufferline = "multiple"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
