theme = "base16_default_dark"

[editor]
scrolloff = 7
cursorline = true
bufferline = "multiple"
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]

[keys.normal.space]
w = ":write"
q = ":quit"

[editor.soft-wrap]
enable = true
max-wrap = 25
